const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { TextDecoder, TextEncoder } = require('node:util');
const root = path.resolve(__dirname, '..');
global.self = globalThis;
for (const file of ['vendor/gis-formats.js', 'layer-normalizer.js', 'parsers/common.js', 'parsers/geojson.js',
  'parsers/kml.js', 'parsers/gpx.js', 'parsers/dxf.js', 'parsers/geotiff.js', 'parsers/xml.js', 'parsers/wmts.js']) {
  vm.runInThisContext(fs.readFileSync(path.join(root, 'js', file), 'utf8'), {filename:file});
}
vm.runInThisContext(fs.readFileSync('/var/www/html/inc/javascript/jszip/jszip3.min.js','utf8'));
vm.runInThisContext(fs.readFileSync('/var/www/html/inc/javascript/shapefilejs/dxfparser.min.js','utf8'));
const file = (name, data) => Object.assign(new Blob([data]), { name });
const kml = '<kml xmlns="http://www.opengis.net/kml/2.2"><Placemark><name>中文</name><Point><coordinates>121,25</coordinates></Point></Placemark></kml>';
const gpx = '<gpx version="1.1" xmlns="http://www.topografix.com/GPX/1/1"><wpt lat="25" lon="121"><name>中文</name></wpt></gpx>';
const cwa = '<cwaopendata xmlns="urn:cwa:gov:tw:cwacommon:0.1"><dataid>O-A0002-001</dataid><sent>2026-09-09T12:20:00+08:00</sent><dataset><Station><StationName>測試站</StationName><StationId>TEST</StationId><ObsTime><DateTime>2026-09-09T12:20:00+08:00</DateTime></ObsTime><GeoInfo><Coordinates><CoordinateName>TWD67</CoordinateName><StationLatitude>24</StationLatitude><StationLongitude>120</StationLongitude></Coordinates><Coordinates><CoordinateName>WGS84</CoordinateName><StationLatitude>25</StationLatitude><StationLongitude>121</StationLongitude></Coordinates></GeoInfo><RainfallElement><Now><Precipitation>0.5</Precipitation></Now></RainfallElement></Station></dataset></cwaopendata>';
const genericXML = '<data><row><name>甲</name><longitude>121.5</longitude><latitude>25.1</latitude></row><row><name>乙</name><longitude>121.6</longitude><latitude>25.2</latitude></row></data>';
const genericXY = '<data><row><name>甲</name><X>300000</X><Y>2700000</Y></row><row><name>乙</name><X>301000</X><Y>2701000</Y></row></data>';
const genericTable = '<data><row><name>甲</name></row><row><name>乙</name></row></data>';
const dxf = '0\nSECTION\n2\nBLOCKS\n0\nBLOCK\n2\nARC_BLOCK\n10\n0\n20\n0\n0\nLWPOLYLINE\n90\n2\n10\n0\n20\n0\n42\n1\n10\n10\n20\n0\n0\nENDBLK\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n0\nINSERT\n2\nARC_BLOCK\n10\n120\n20\n24\n41\n2\n42\n2\n50\n90\n70\n2\n71\n2\n44\n20\n45\n30\n0\nENDSEC\n0\nEOF\n'.replaceAll('\\n','\n');
(async () => {
 const result = parseGeoJSON({type:'Feature',geometry:{type:'Point',coordinates:[121,25]},properties:{name:'<img onerror=1>'}},'point',[]);
 assert.deepEqual(result.bounds,[121,25,121,25]);
 assert.throws(()=>parseGeoJSON({type:'Point',coordinates:['bad',25]},'bad'));
 assert.throws(()=>FormatHelpers.xml('<!DOCTYPE kml><kml/>','kml'));
 assert.throws(()=>FormatHelpers.xml('<kml><Placemark></kml>','kml'));
 assert.equal(FormatHelpers.child({},'missing'),'');
 assert.equal((await parseKML(file('test.kml',kml),'auto'))[0].count,1);
 const damaged = (await parseKML(file('damaged.kml',kml.replace('中文','圖層�')),'auto'))[0];
 assert.equal(damaged.count,1);
 assert.ok(damaged.warnings.some(message=>message.includes('替代字元')));
 assert.ok(damaged.preview[0].includes('圖層�'));
 const invalidCoordinates = (await parseKML(file('projected.kml',kml.replace('121,25','-129,2737200')),'auto'))[0];
 assert.match(invalidCoordinates.coordinateLabel,/超出合法/);
 assert.match(invalidCoordinates.warnings[0],/匯出錯誤/);
 const damagedGPX = await parseGPX(file('damaged.gpx',gpx.replace('中文','航點�')),'auto');
 assert.equal(damagedGPX.count,1);
 assert.ok(damagedGPX.warnings.some(message=>message.includes('替代字元')));
 const zip = new JSZip(); zip.file('doc.kml', kml);
 assert.equal((await parseKML(file('test.kmz',await zip.generateAsync({type:'uint8array'})),'auto'))[0].count,1);
 assert.equal((await parseGPX(file('test.gpx',gpx),'auto')).count,1);
 global.includeMap = true;
 const parsedXML = await parseOpenDataXML(file('stations.xml',cwa),'auto');
 assert.deepEqual(parsedXML.bounds,[121,25,121,25]);
 assert.equal(parsedXML.mapData.crs,'EPSG:4326');
 assert.equal(parsedXML.preview[0][0],'測試站');
 assert.match(parsedXML.sourceCRS,/WGS84/);
 await assert.rejects(() => parseOpenDataXML(file('other.xml','<root/>'),'auto'),/重複標籤/);
 const parsedGeneric = await parseOpenDataXML(file('generic.xml',genericXML),'auto');
 assert.deepEqual(parsedGeneric.bounds,[121.5,25.1,121.6,25.2]);
 assert.equal(parsedGeneric.mapData.crs,'EPSG:4326');
 assert.match(parsedGeneric.details[0],/<row>/);
 const parsedXY = await parseOpenDataXML(file('xy.xml',genericXY),'auto');
 assert.equal(parsedXY.mapData.crs,null);
 assert.match(parsedXY.warnings.at(-1),/指定資料來源座標系統/);
 const parsedTable = await parseOpenDataXML(file('table.xml',genericTable),'auto');
 assert.equal(parsedTable.mapData,null);
 assert.match(parsedTable.warnings.at(-1),/僅顯示屬性預覽/);
 const parsedDxf = await parseDXF(file('test.dxf',dxf),'auto');
 assert.equal(parsedDxf.count,1);
 assert.equal(parsedDxf.mapData.collection.features.length,4);
 assert.deepEqual(parsedDxf.bounds,[120,24,150,74]);
 assert.ok(parsedDxf.mapData.collection.features.every(feature => feature.geometry.coordinates.length > 2));
 assert.match(parsedDxf.details.at(-1),/展開 INSERT：4 次/);
 global.includeMap = false;
 const raster = await parseGeoTIFF(file('sample.tif', fs.readFileSync(path.join(__dirname,'fixtures/sample.tif'))));
 assert.deepEqual(raster.bounds,[120,23,122,25]);
 assert.equal(raster.preview[0][3],'1');
 const caps='<Capabilities xmlns="http://www.opengis.net/wmts/1.0" xmlns:ows="http://www.opengis.net/ows/1.1" version="1.0.0"><Contents><Layer><ows:Identifier>test</ows:Identifier><ows:Title>測試圖層</ows:Title><Format>image/png</Format><TileMatrixSetLink><TileMatrixSet>grid</TileMatrixSet></TileMatrixSetLink></Layer><TileMatrixSet><ows:Identifier>grid</ows:Identifier></TileMatrixSet></Contents></Capabilities>';
 global.fetch = async () => new Response(caps);
 assert.equal((await parseWMTS('https://example.test/wmts?service=WMTS'))[0].name,'測試圖層');
 global.fetch = async () => { throw new Error('network'); };
 await assert.rejects(()=>parseWMTS('https://example.test/wmts'),/CORS/);
 console.log('GeoJSON, KML/KMZ, GPX, DXF, GeoTIFF, XML rejection and WMTS checks passed');
})().catch(error=>{console.error(error);process.exit(1)});
